# This is used by Github actions to ensure docker images build properly.
version: "3.9"

services:
  ilovemoney:
    build: .
  sut:
    image: alpine
    command: sh -c 'sleep 5; wget -qO- ilovemoney:8000/healthcheck | grep "OK"'
    depends_on:
      - ilovemoney
